name: Deploy Documentation
on:
  push:
    branches: [ docs ]  # Change to your default branch if different
  pull_request:
    branches: [ docs ]

permissions:
  contents: write
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for setuptools-scm
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]
      
      - name: Build docs
        run: mkdocs build
      
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force