site_name: FastPG Documentation
site_description: Lightweight async ORM for PostgreSQL

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: light green
  font:
    text: Source Code Pro
    code: Source Code Pro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.highlight
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/hacker.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference: api.md
  - Examples: examples.md