site_name: FastPG Documentation
theme:
  name: material
  palette:
    scheme: slate  # Dark theme
    primary: green  # Green accent like hacker theme
    accent: green
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.highlight
    - content.code.copy

extra_css:
  - stylesheets/hacker.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences