site_name: FastPG Documentation
site_description: Lightweight async ORM for PostgreSQL
nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference: api.md
  - Examples: examples.md