FROM postgres:13.5

COPY dockerify/db/pg13/setup-replica.sh /docker-entrypoint-initdb.d/

RUN chmod +x dockerify/db/pg13/replica-entrypoint.sh
RUN chmod +x /docker-entrypoint-initdb.d/setup-replica.sh